### ISSUE TITLE
Parse error [arm64]

### ISSUE THREAD

**Issue by Just5KY** [xavier-hernandez/goaccess-for-nginxproxymanager#12]
Built an image for arm64
docker build -t justsky/goaccess-for-nginxproxymanager .

Using this compose 
```yml
  goaccess:
    image: justsky/goaccess-for-nginxproxymanager
    container_name: goaccess
    restart: unless-stopped
    ports:
      - 7880:7880
    volumes:
      - $DOCKERDIR/npm/data/logs:/opt/log
    environment:
      - PUID=0
      - PGID=0
      - TZ=$TZ
```

seeing the following parse error in logs
[goaccess-2022-03-02T03-03-34.log](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/files/8166313/goaccess-2022-03-02T03-03-34.log)
