### ISSUE TITLE
Stop working on parse errors

### ISSUE THREAD

**Issue by webysther** [xavier-hernandez/goaccess-for-nginxproxymanager#156]
Hi @xavier-hernandez, I have the same container (latest) a few while now and everything works just fine, but for some reason after redeploy last week to change the healthcheck in my container it stop working, for me is strange because get errors in same old log with same container:

```
==409== GoAccess - version 1.7.2 - Jul  3 2023 01:17:55
==409== Config file: /goaccess-config/goaccess.conf
==409== https://goaccess.io - <hello@goaccess.io>
==409== Released under the MIT License.
==409== FILE: /goaccess-logs/archives/proxy-host-24_access.log.4
==409== Parsed 1 lines producing the following errors:
==409==
==409== Token '-' doesn't match specifier '%m'
```

It still in the same error without stop and dont move to new file, this one for example have only 20KB.

```yml
version: '3.9'

services:
  goaccess-all: &goaccess
    image: xavierh/goaccess-for-nginxproxymanager:v1.1.18
    container_name: app-analytics-log-all
    env_file: ../goaccess/.env
    cpuset: '0'
    networks:
      goaccess:
    expose:
      - 7880
    volumes:
      - "$LOG/nginx-proxy-manager:/opt/log:ro"
    tmpfs:
      - /opt/custom
    healthcheck:
      test: [
        "CMD", "wget", "--spider", "-q", 
        "localhost:7880"
      ]
      interval: 300s
      retries: 5
      timeout: 10s
    restart: unless-stopped
```

```env
PUID=1026
PGID=101
TZ=Europe/Rome
LOG=/volumeUSB2/usbshare/cache/log/docker
LOG_TYPE=NPM
```

As you can see, the cpu still high for while but stop, the loop still going...

![image](https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager/assets/750007/d7e9dfe5-6de8-44b9-89d0-0d4c8024bc2e)

[log file](https://paste.07f.de/?6c28f607602d018e#8AZQBw8iHPvoyBWmhN8Wu2cSQayQLgNkM52WJ4yRKdjk)

Do you have any clue?
