### ISSUE TITLE
Setup GitHub Actions for automated multi-arch container build and push to dockerhub

### ISSUE THREAD

**Issue by Just5KY** [xavier-hernandez/goaccess-for-nginxproxymanager#34]
You can use GitHub actions to build multi-arch images
https://github.com/marketplace/actions/docker-setup-buildx

Found a tutorial on how to do it.
https://youtu.be/cXagGh_7TH4

I mixed both together and made this on another repo
 https://github.com/Just5KY/scalyr-tool/blob/main/.github/workflows/dockerhub.yml

I can create a PR if you want

**Comment by xavier-hernandez** [comment]
@Just5KY I was actually looking at github actions recently but didn't really have time. I was looking at something created by crazy-max but yours looks super easier. Feel free to create a PR. Once you complete your PR I'll try it out on a different repo of mine and make sure everything works then I'll approve it. Don't want to accidentally mess up the images :P

What does this do, schedule an auto build?
schedule:
    - cron: '50 15 * * *'

**Comment by Just5KY** [comment]
```yml
on:
  schedule:
    - cron: '50 15 * * *'      #Build image when dailt at 15:50 but im not sure which timezone.
  push:
    branches: [ main ]        #Build image when there is a comitt push
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]       #Build image after a pull request is accepted
  workflow_dispatch:       #Adds a button to manually build image in GitHub actions page.
```

I am still playing around with it, but it works

**Comment by Just5KY** [comment]
I also found this
https://github.com/Yooooomi/your_spotify/blob/master/.github/workflows/client.yml

Its clear implementation, but it does not have automatic builds

**Comment by Just5KY** [comment]
You can just add this to your test repo like  `test_repo/.github/workflows/FILENAME.yml`

you need to create a GitHub secret for your dockerhub access token with the name `DOCKER_TOKEN`

```yml
name: Docker multi-arch build and push

on:
  schedule:
    - cron: '50 15 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: test_image_name

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Docker login
        run: docker login -u DOCKER_USERNAME -p ${{ secrets.DOCKER_TOKEN }} 
        
      - name: Build the Docker image
        run: docker buildx build --push --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8  --tag DOCKER_USERNAME /test_image_name .
```
